name: Test Pull Request
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Git
        env:
          GIT_AUTHOR_NAME: Richard Santos
          GIT_AUTHOR_EMAIL: richard.santos21@hotmail.com
          GIT_COMMITTER_NAME: Richard Santos
          GIT_COMMITTER_EMAIL: richard.santos21@hotmail.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
      - name: Push to main branch
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          ssh -i $SSH_KEY git push origin development:main