name: Test Pull Request
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  deploy:
    run: |
      git config user.name "Richard Santos"
      git config user.email "richard.santos21@hotmail.com"
      git push origin development:main